### ISSUE TITLE
Authentication using Fingerprint

### ISSUE THREAD

**Issue by IzzDarki** [IzzDarki/Wallet#65]
Instead of app password

**Comment by Ammar-Ishfaq** [comment]
Hello @IzzDarki, have you considered enabling fingerprint login for the wallet app? 
I've noticed that it currently lacks a security layer, allowing access without authentication.

**Comment by IzzDarki** [comment]
Hi @Ammar-Ishfaq, I am currently implementing authentication using an app password (issues #55, #62). Most of it is already available on the version-2.2.0 development branch. I don't know how long it will take to complete all features of version-2.2.0, but in one way or another all currently developed features should end up on the master branch in a few weeks. However, I don't plan to implement the support for fingerprint authentication (#65) at the moment.
Until then using an app locker could be a good alternative. Some android versions have a build-in app locker.

**Comment by Ammar-Ishfaq** [comment]
Hi @IzzDarki, Can i implement this feature and create a pull request for it?

**Comment by IzzDarki** [comment]
Hi @Ammar-Ishfaq, that would be great.
If you want to implement it, you can start from the latest commit on the version-2.2.0 branch, where authentication using an app password is already implemented.

Just that you know, authentication is implemented mainly in
logic.AuthenticationLogic,
logic.AuthenticatedAppCompatActivity (Base class for all activities that require the user to be authenticated),
preferences.AuthenticationPreferences (responsible for saving authentication related data persistently to the device) and the corresponding interface preferences.AuthenticationStorageInterface,
ui.authentication.AuthenticationActivity (activity that asks the user to authenticate),
ui.settings.DisableAuthenticationFragment
and ui.settings.SetupAuthenticationFragment.

The project is currently missing a license. I will be using the GPL3 License (because a dependency also uses this license). So if you want to contribute I assume you're fine that your code will be published under that license.

Thanks a lot for contributing

**Comment by Ammar-Ishfaq** [comment]
Thank you @IzzDarki for updating, I'll work on it. In case of questions, I will ping you here.

**Comment by Ammar-Ishfaq** [comment]
@IzzDarki  FYI is it right?
The work we are going to implement is just to add fingerprint authentication when a user opens this "Wallet" App.

**Comment by IzzDarki** [comment]
Yes that's right. It would be nice if the user could choose between 1. no authentication, 2. app password or 3. fingerprint. The first two are already implemented. It would be great if you could find some way to add the option to use fingerprint to the app settings. Maybe add this functionality to the SetupAuthenticationFragment.

**Comment by Ammar-Ishfaq** [comment]
sure

**Comment by Ammar-Ishfaq** [comment]
I've already started work on it but will look on it once done

**Comment by Ammar-Ishfaq** [comment]
Hello @IzzDarki, I've just submitted PR #68 for the Fingerprint functionality. Whenever you have some time, could you please take a look and let me know your thoughts? If everything looks good, I would greatly appreciate it if you could merge it for me. Thank you!

**Comment by IzzDarki** [comment]
I made some small changes and merged your pull request. Thanks a lot for your help 😊
